# Regenerate version.h from the current git state. Runs on every build;
# only rewrites the file when the version changed, so incremental builds
# stay incremental.
execute_process(
    COMMAND git describe --always --dirty
    WORKING_DIRECTORY ${SOURCE_DIR}
    OUTPUT_VARIABLE GIT_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE GIT_RESULT)

if(NOT GIT_RESULT EQUAL 0 OR GIT_VERSION STREQUAL "")
    set(GIT_VERSION "dev")
endif()

set(CONTENT "// Copyright (C) 2026 Justin Hamilton
// SPDX-License-Identifier: GPL-3.0-or-later

/** @file
 *  Build version stamp, generated by cmake/GitVersion.cmake. Do not edit.
 */

#ifndef _SD_VERSION_H
#define _SD_VERSION_H

#define GAME_VERSION \"${GIT_VERSION}\"

#endif
")

set(OLD "")
if(EXISTS ${OUTPUT_FILE})
    file(READ ${OUTPUT_FILE} OLD)
endif()

if(NOT CONTENT STREQUAL OLD)
    file(WRITE ${OUTPUT_FILE} "${CONTENT}")
endif()
